add example of building with approval

diff --git a/.github/workflows/buildWithApprovalStep.yml b/.github/workflows/buildWithApprovalStep.yml
--- a/.github/workflows/buildWithApprovalStep.yml
+++ b/.github/workflows/buildWithApprovalStep.yml
@@ -1,13 +1,11 @@
+# This demonstrates how to use terraform with
 
-name: petertestbuild4.yml
-run-name: ${{ github.actor }} file petertestbuild4.yml
+name: buildWithApprovalStep.yml
+run-name: ${{ github.actor }} file buildWithApprovalStep.yml
 
 on: workflow_dispatch
 
 jobs:
-
-
-
   job1:
     runs-on: ubuntu-latest
     outputs:
@@ -17,10 +15,10 @@ jobs:
       - name: Set variables
         id: set_variable
         run: |
-            #  echo "::set-output name=my_variable1::123"
-            echo "my_variable1=123" >> ${GITHUB_OUTPUT}
-            echo "my_variable2=xenv1" >> ${GITHUB_OUTPUT}
-            # echo "my_variable2=env1" >> ${GITHUB_OUTPUT}
+          #  echo "::set-output name=my_variable1::123"
+          echo "my_variable1=123" >> ${GITHUB_OUTPUT}
+          echo "my_variable2=xenv1" >> ${GITHUB_OUTPUT}
+          # echo "my_variable2=env1" >> ${GITHUB_OUTPUT}
 
   job2:
     runs-on: ubuntu-latest
@@ -28,20 +26,17 @@ jobs:
     steps:
       - name: Use variable from job1
         run: |
-            echo "  job1 my_variable1 = ${{needs.job1.outputs.my_variable1}}"
-            echo "  job1 my_variable2 = ${{needs.job1.outputs.my_variable2}}"
-
+          echo "  job1 my_variable1 = ${{needs.job1.outputs.my_variable1}}"
+          echo "  job1 my_variable2 = ${{needs.job1.outputs.my_variable2}}"
 
   terraform_init:
     runs-on: ubuntu-latest
     steps:
-
       - name: tfstep1
         run: ls -lart || true
 
       - name: tfstep2
         run: ls -lart .terraform || true
-
 
       - name: Checkout code
         uses: actions/checkout@v4
@@ -52,10 +47,8 @@ jobs:
       - name: tfstep4
         run: ls -lart .terraform || true
 
- 
       - name: Get Terraform version
         run: terraform --version || true
-
 
       - name: Initialize Terraform
         run: terraform init
@@ -73,12 +66,10 @@ jobs:
       - name: tfstep6b
         run: ls -lart terraform/config/.terraform || true
 
-
   terraform_apply1:
     runs-on: ubuntu-latest
     needs: terraform_init
     steps:
-
       - name: tfstep1
         run: ls -lart || true
 
@@ -94,7 +85,6 @@ jobs:
       - name: tfstep4
         run: ls -lart .terraform || true
 
-
       - name: Apply Terraform 1
         run: terraform apply -auto-approve || true
         working-directory: terraform/config
@@ -105,14 +95,11 @@ jobs:
       - name: tfstep6
         run: ls -lart .terraform || true
 
-
-
       - name: Initialize Terraform
         run: terraform init
         working-directory: terraform/config
-        # this is same as 
-        # terraform -chdir=terraform/config init 
-
+        # this is same as
+        # terraform -chdir=terraform/config init
 
       - name: tfstep7
         run: ls -lart || true
@@ -123,45 +110,48 @@ jobs:
       - name: tfstep8a
         run: ls -lart my_folder || true
 
-
       - name: Terraform Plan 1
         run: terraform plan || true
         working-directory: terraform/config
-        # this is same as 
-        # terraform -chdir=terraform/config plan 
-
+        # this is same as
+        # terraform -chdir=terraform/config plan
 
       - name: Terraform Plan 2
         run: terraform plan -out=tfplan || true
         working-directory: terraform/config
-        # this is same as 
-        # terraform -chdir=terraform/config -out=tfplan plan 
+        # this is same as
+        # terraform -chdir=terraform/config -out=tfplan plan
 
       - name: tfplanstep1
         run: |
-            ls -lart || true
-            ls -lart tfplan || true
-            ls -lart terraform/config/tfplan || true
-            ls -lart terraform/config/ || true
-
+          ls -lart || true
+          ls -lart tfplan || true
+          ls -lart terraform/config/tfplan || true
+          ls -lart terraform/config/ || true
 
       - name: Terraform Plan 2
-        run: terraform plan -out=tfplan &> tpf1.txt|| true
+
+        # NOTE - you MUST include -no-color if you're going to parse the file !
+        # Without that, the file will include terminal formatting codes (and the parse will probably fail)
+        #
+        # https://developer.hashicorp.com/terraform/cli/commands/plan
+        # Use this if you are running Terraform in a context where its output will be rendered by a system that cannot interpret terminal formatting
+
+        run: terraform plan -out=tfplan  -no-color &> tpf1.txt|| true
         working-directory: terraform/config
-        # this is same as 
+        # this is same as
+        # cd terraform/config && terraform plan -out=tfplan &> tpf1.txt
         # terraform -chdir=terraform/config plan -out=tfplan &> terraform/config/tpf1.txt
 
       - name: tfplanstep2
         run: |
-            ls -lart || true
-            ls -lart tfplan || true
-            ls -lart terraform/config/tfplan || true
-            ls -lart terraform/config/ || true
-            ls -lart terraform/config/tpf1.txt || true
-            cat terraform/config/tpf1.txt || true
-            grep '2 to add, 0 to change, 0 to destroy' terraform/config/tpf1.txt || true
-
-
+          ls -lart || true
+          ls -lart tfplan || true
+          ls -lart terraform/config/tfplan || true
+          ls -lart terraform/config/ || true
+          ls -lart terraform/config/tpf1.txt || true
+          cat terraform/config/tpf1.txt || true
+          grep '2 to add, 0 to change, 0 to destroy' terraform/config/tpf1.txt || true
 
         # This will fail
       - name: Apply Terraform 2
@@ -177,16 +167,15 @@ jobs:
         run: terraform apply -input=false  || true
         working-directory: terraform/config
 
+      # terraform init -input=false to initialize the working directory.
+      # terraform plan -out=tfplan -input=false to create a plan and save it to the local file tfplan.
+      # terraform apply -input=false tfplan to apply the plan stored in the file tfplan.
+      #
+      #     environment:
+      #       name: ${{ if: needs.job1.result == 'failure' }}  # Conditional environment
+      #       url: ${{ secrets.TEST_URL }} # Conditional environment URL
 
-# terraform init -input=false to initialize the working directory.
-# terraform plan -out=tfplan -input=false to create a plan and save it to the local file tfplan.
-# terraform apply -input=false tfplan to apply the plan stored in the file tfplan.
-# 
-#     environment:
-#       name: ${{ if: needs.job1.result == 'failure' }}  # Conditional environment
-#       url: ${{ secrets.TEST_URL }} # Conditional environment URL
-
-# terraform plan -out=tfplan -input=false
+      # terraform plan -out=tfplan -input=false
 
       - name: tfstep9
         run: ls -lart || true
@@ -197,10 +186,8 @@ jobs:
       - name: tfstep9b
         run: ls -lart terraform/config/.terraform || true
 
-
       - name: tfstep10
         run: ls -lart .terraform || true
-
 
       - name: tfstep10a
         run: ls -lart my_folder || true
@@ -208,43 +195,38 @@ jobs:
       - name: tfstep10a
         run: cat my_folder/my_file.txt || true
 
-
       - name: tfstep11
         run: ls -lart terraform/config/my_folder || true
 
       - name: tfstep12
         run: cat terraform/config/my_folder/my_file.txt || true
 
-
-
   terraform_apply2:
     runs-on: ubuntu-latest
     needs: [job1, terraform_apply1]
-#     environment: 'env1'
+    #     environment: 'env1'
     environment:
-#         name:  'env1'
-        name:  "${{needs.job1.outputs.my_variable2}}"
-#         url: https://example.com
-#         url: any-old_string_here
-        url: https://any-old_string_here
+      #         name:  'env1'
+      name: "${{needs.job1.outputs.my_variable2}}"
+      #         url: https://example.com
+      #         url: any-old_string_here
+      url: https://any-old_string_here
 
     steps:
-
       - name: tfstep00
         run: |
-            echo "  needs.job1.outputs.my_variable1 = ${{needs.job1.outputs.my_variable1}}"
-            echo "  needs.job1.outputs.my_variable2 = ${{needs.job1.outputs.my_variable2}}"
+          echo "  needs.job1.outputs.my_variable1 = ${{needs.job1.outputs.my_variable1}}"
+          echo "  needs.job1.outputs.my_variable2 = ${{needs.job1.outputs.my_variable2}}"
 
       - name: "tfstep01"
         run: |
-            echo "  needs.job1.outputs.my_variable1 = ${{needs.job1.outputs.my_variable1}}"
-            echo "  needs.job1.outputs.my_variable2 = ${{needs.job1.outputs.my_variable2}}"
+          echo "  needs.job1.outputs.my_variable1 = ${{needs.job1.outputs.my_variable1}}"
+          echo "  needs.job1.outputs.my_variable2 = ${{needs.job1.outputs.my_variable2}}"
 
       - name: "tfstep02_${{needs.job1.outputs.my_variable2}}"
         run: |
-            echo "  needs.job1.outputs.my_variable1 = ${{needs.job1.outputs.my_variable1}}"
-            echo "  needs.job1.outputs.my_variable2 = ${{needs.job1.outputs.my_variable2}}"
-
+          echo "  needs.job1.outputs.my_variable1 = ${{needs.job1.outputs.my_variable1}}"
+          echo "  needs.job1.outputs.my_variable2 = ${{needs.job1.outputs.my_variable2}}"
 
       - name: tfstep1
         run: ls -lart || true
@@ -261,7 +243,6 @@ jobs:
       - name: tfstep4
         run: ls -lart .terraform || true
 
-
       - name: Apply Terraform 1
         run: terraform apply -auto-approve || true
         working-directory: terraform/config
@@ -272,12 +253,9 @@ jobs:
       - name: tfstep6
         run: ls -lart .terraform || true
 
-
-
       - name: Initialize Terraform
         run: terraform init
         working-directory: terraform/config
-
 
       - name: tfstep7
         run: ls -lart || true
@@ -288,11 +266,9 @@ jobs:
       - name: tfstep8a
         run: ls -lart my_folder || true
 
-
       - name: Apply Terraform 2
         run: terraform apply -auto-approve
         working-directory: terraform/config
-
 
       - name: tfstep9
         run: ls -lart || true
@@ -303,10 +279,8 @@ jobs:
       - name: tfstep9b
         run: ls -lart terraform/config/.terraform || true
 
-
       - name: tfstep10
         run: ls -lart .terraform || true
-
 
       - name: tfstep10a
         run: ls -lart my_folder || true
@@ -314,11 +288,8 @@ jobs:
       - name: tfstep10a
         run: cat my_folder/my_file.txt || true
 
-
       - name: tfstep11
         run: ls -lart terraform/config/my_folder || true
 
       - name: tfstep12
         run: cat terraform/config/my_folder/my_file.txt || true
-
-
